Repository SWM-KAWAI-MANS/party-run-battle-service, pull requests merged in 2023-09, with the labels that each got.

#43 feat: 전체 메서드에 대해 실행 로그를 작성하는 Advisor 구현
  src/main/java/online/partyrun/partyrunbattleservice/global/advisor/LogAdvisor.java
Labels: ✨ 기능

#44 쿼리에 elemMatch가 사용되도록 변경
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java
Labels: ♻️ 리팩토링

#45 로깅을 구체화한다.
  build.gradle
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleEventHandler.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleWebsocketController.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleCreateRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleIdResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleStartedResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/RunnerDistanceResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/RunnerFinishedResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/WebSocketEventListener.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/global/advisor/LogAdvisor.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/CachedHttpServletRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/CachedServletInputStream.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/LogAdvisor.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/Logging.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/RequestCachingFilter.java
  src/main/resources/logback-spring.xml
Labels: ✨ 기능

#46 http 로그 출력 방식을 변경한다.
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/CachedHttpServletRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/CachedServletInputStream.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/RequestLoggingFilter.java
  src/main/resources/logback-spring.xml
Labels: ♻️ 리팩토링, ✨ 기능

#47 error 로그 발생 시, slack으로 알림 전송
  build.gradle
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/RequestLogFormatter.java
  src/main/java/online/partyrun/partyrunbattleservice/global/logging/RequestLoggingFilter.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨ 기능

#48 battleInterceptor BATTLE_TOPIC_PREFIX 변경
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/config/BattleChannelInterceptor.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleWebsocketController.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java
Labels: ♻️ 리팩토링

#49 배틀 과정 중 예외 발생 시, 로깅 처리
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleMessageControllerAdvice.java
Labels: ✨ 기능

#50 feat: redis cluster 연결을 prd 환경 변수 변경
  src/main/java/online/partyrun/partyrunbattleservice/global/config/RedissonConfig.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunbattleservice/domain/battle/config/TestRedissonConfiguration.java
Labels: ✨ 기능

#52 error 로그 메시지 변경
  src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleMessageControllerAdvice.java
Labels: ✨ 기능

#53 거리 계산 로직 수정
  src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java
Labels: 🐛 버그

#54 redisson config 수정
  src/main/java/online/partyrun/partyrunbattleservice/global/config/RedissonConfig.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/battle/config/TestRedissonConfiguration.java
Labels: ♻️ 리팩토링

#55 싱글 모드 기록을 저장한다.
  src/docs/asciidoc/battle.adoc
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleController.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleIdResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/Single.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/SingleRunnerRecordEmptyException.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/repository/SingleRepository.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java
  src/main/java/online/partyrun/partyrunbattleservice/global/controller/HttpControllerAdvice.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleControllerTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/SingleTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleServiceTest.java
Labels: ✨ 기능

#56 aws redis cluster 연결 방식 변경
  src/main/java/online/partyrun/partyrunbattleservice/global/config/RedissonConfig.java
  src/main/resources/application.yml
Labels: 🐛 버그

#59 refactor : SingleRunnerRecordsRequest 메서드명 변경
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequestTest.java
Labels: ♻️ 리팩토링, 🐛 버그

#58 refactor : IllegalRunningTimeException 디렉터리 이동
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/RunningTime.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/IllegalRunningTimeException.java
Labels: ♻️ 리팩토링

#57 single 엔티티에 RunningTime 추가
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/RunningTimeRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequest.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/RunningTime.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/Single.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/IllegalRunningTimeException.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleControllerTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/RunningTimeTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/SingleTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleServiceTest.java
Labels: ✨ 기능

#61 싱글 결과 조회 API 구현
  src/docs/asciidoc/battle.adoc
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleController.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/RunningTimeResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleResponse.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/Single.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/InvalidSingleOwnerException.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/SingleNotFoundException.java
  src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleControllerTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/SingleTest.java
  src/test/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleServiceTest.java
  src/test/java/online/partyrun/partyrunbattleservice/global/ServiceTest.java
Labels: ✨ 기능

#64 prd ci cd workflow 추가
  .github/workflows/build-docker-image-prd.yml
  .github/workflows/cd-prd.yml
Labels: 🏭인프라
